import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryWrapper from "@/components/ReactQueryWrapper";
import { Toaster } from "@/components/ui/sonner";
import PayPalProvider from "@/components/PayPalProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MovieApp",
  description: "Generated by Ritech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PayPalProvider>
          <ReactQueryWrapper>
            {children}
            <Toaster />
          </ReactQueryWrapper>
        </PayPalProvider>
      </body>
    </html>
  );
}
